name: 'Workflow Wait'
description: 'This action triggers a workflow in another repository and waits for the result.'
author: 'Rimz'
branding:
  icon: 'arrow-right'
  color: 'yellow'
inputs:
  org:
    description: "The owner of the repository where the workflow is contained."
    required: true
  repository:
    description: "The repository where the workflow is contained."
    required: true
  workflow_file_name:
    description: "The reference point. For example, you could use main.yml."
    required: true
  email:
    description: 'Payload to pass to the workflow, must be a JSON string'
    required: true
  repo_token:
    description: "The Github access token with access to the repository. It is recommended you put this token under secrets."
    required: true
outputs:
  workflow_id:
    description: The ID of the workflow that was triggered by this action
  workflow_url:
    description: The URL of the workflow that was triggered by this action
  conclusion:
    description: Conclusion of the job, i.e pass/failure
runs:
  using: 'docker'
  image: 'Dockerfile'
