name: Build

on:
  workflow_dispatch:

jobs:
  self-test:
    name: Run self-test
    runs-on: ubuntu-latest
    steps:
      - uses: robinatwork1999/triggersync@master-v46
        with:
            org: robinatwork1999
            repository: product-commerce
            repo_token: ${{ secrets.TOKEN }}
            workflow_file_name: cc.yml
            email: 11111
